version: '3.8'

services:
  # 1. The Database (The Car)
  db:
    image: postgres:15-alpine
    container_name: cloudmetrics_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cloudmetrics_db
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_config.conf:/etc/postgresql/postgresql.conf

  # 2. Database Viewer (Optional tool to see tables)
  pgadmin:
    image: dpage/pgadmin4
    container_name: cloudmetrics_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db